zai: ENC[AES256_GCM,data:bumNRpP7bSzhGGFrmzBFAo+fBLhci80Df+hFj8scs5WAge0WD375z7Vcfzw9XGNHOg==,iv:oFARAu1kxWh0XXTovPtQuq3waVGSHwjso6rMW5PFzq0=,tag:SbdfCvuB0o8GBMbNp0mmlw==,type:str]
sops:
    age:
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a0JQNmxZWS93aUpsczlW
            czYyZ2Frcnh0MWhOZVdsa25xNHp5Y0VYZkJVClJKbFNKUE5sYzNMU0FwNVE3Y2Z2
            U0RBU3ZUNmpIejJ4eDVVZFZLUEpJdkUKLS0tIENkYXhhWWJpMlczeWNOd2xTd1R1
            Z2JHbFpSaXN4Tk52TnZ0VS9qUml3QzAKifQhQMYKEeG39Y4PJek459JUUjdVoLa1
            ak+0GL2577Aol4OvbN1NYT2ZGR43if3FBPGhsmMJ4tZzdhRQzCRSxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T21:01:00Z"
    mac: ENC[AES256_GCM,data:tMEKKmyH/u5McSdZ7BaXliOhEuDUk8D33+p1mGkzB+dzkEL+VWA8gHmiwHvYrcgfyppGSLt2zv68fSmFMUEYRtAweA7LW6h5eQ12TSoywAvBPfRtBr1erTcO4IC5p/sBMHwh87q+o433CA1DdaNLo+wuzGPQobrV+e8fzbQCfis=,iv:5XmjlxSXAPACZR/pPTGec+oohGrKEgU97ZjtcDHqKhA=,tag:DWRBCZMD9PYxyzX9ZKKrXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
